# theme: jekyll-theme-dinky
theme: jekyll-theme-cayman
google_analytics: ['UA-128916623-7']
title: [AWS CDK Poc]
description: [Deploying AWS resources with AWS Codepipeline written in AWS CDK typescript]
github:
  home_url: https://rupeshtiwari.com